import React, { useState } from 'react';
import { ArrowUpRight, Check, ChevronDown, ChevronRight, CirclePlay, Dumbbell, HeartPulse, Menu, Search, ShieldCheck, Star, Trophy, X, Apple } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const img = { athlete: '/assets/workout.png', yoga: '/assets/yoga.jpg', food: '/assets/nutrition.png', coach: '/assets/coach.jpg' };
const cats = [['Musculação', Dumbbell], ['Yoga', HeartPulse], ['Basquete', Trophy], ['Nutrição', Apple], ['Recuperação', HeartPulse], ['Lesões', ShieldCheck]];
const videos = [
  ['Hipertrofia inteligente: peito e tríceps', 'Musculação', '32 min', img.athlete], ['Yoga para mobilidade do quadril', 'Yoga', '24 min', img.yoga],
  ['Controle de bola para armadores', 'Basquete', '18 min', img.athlete], ['Sono: o treino invisível', 'Recuperação', '14 min', img.yoga],
  ['Proteína sem complicação', 'Nutrição', '20 min', img.food], ['Prevenção de lesões no joelho', 'Lesões', '27 min', img.coach]
];

function App() { const [page, setPage] = useState('home'); const [menu, setMenu] = useState(false); const go = next => { setPage(next); setMenu(false); window.scrollTo(0, 0); }; return <div className="site"><Header page={page} go={go} menu={menu} setMenu={setMenu} />{page === 'home' && <Home go={go} />}{page === 'explorar' && <Explore go={go} />}{page === 'planos' && <Plans go={go} />}{page === 'profissionais' && <Professional go={go} />}{page === 'trilhas' && <Trails go={go} />}{page === 'detalhe' && <Detail go={go} />}{page === 'cadastro' && <Signup />}{page !== 'cadastro' && <Footer />}</div>; }
function Header({ page, go, menu, setMenu }) { return <header className="header"><button className="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button><button className="logo" onClick={() => go('home')}><span>◉</span> WellFlix</button><nav className={menu ? 'nav open' : 'nav'}><button className={page === 'home' ? 'active' : ''} onClick={() => go('home')}>Início</button><button className={page === 'explorar' ? 'active' : ''} onClick={() => go('explorar')}>Explorar</button><button className={page === 'planos' ? 'active' : ''} onClick={() => go('planos')}>Planos</button><button className={page === 'profissionais' ? 'active' : ''} onClick={() => go('profissionais')}>Profissionais</button><button className={page === 'trilhas' ? 'active' : ''} onClick={() => go('trilhas')}>Minhas trilhas</button></nav><div className="header-actions"><div className="header-search"><Search size={14} /><input placeholder="Buscar treinos, atletas..." /></div><button className="login">Entrar</button><button className="green small" onClick={() => go('cadastro')}>Começar grátis <ArrowUpRight size={13} /></button></div></header>; }
function Home({ go }) { return <main><section className="hero wrap"><div className="hero-copy"><span className="pill">◉ CONTEÚDO 100% CERTIFICADO</span><h1>Seu próximo nível<br />começa com<br />orientação certa.</h1><p>Treinos, nutrição e recuperação guiados por profissionais verificados. Evolua com conteúdo em que você pode confiar.</p><div className="actions"><button className="green" onClick={() => go('explorar')}>Explorar conteúdos <ArrowUpRight size={15} /></button><button className="dark-button" onClick={() => go('planos')}>Conhecer planos</button></div><div className="social-proof"><span>●●●</span> +18 mil atletas já estão evoluindo</div></div><div className="hero-art"><img src={img.athlete} alt="Atleta em movimento" /><div className="featured"><span>EM DESTAQUE · 18 MIN</span><strong>Explosão e velocidade para atletas</strong><small>Com Lucas Freire <ChevronRight size={12} /></small></div></div></section><section className="section wrap"><SectionTitle eyebrow="ENCONTRE SEU FOCO" title="Treine do seu jeito" action="Ver todas as categorias →" /><div className="categories">{cats.map(([name, Icon], i) => <button className={i === 0 ? 'category selected' : 'category'} key={name}><Icon size={18} /><strong>{name}</strong></button>)}</div></section><section className="section wrap"><SectionTitle eyebrow="EM ALTA" title="Conteúdos que movem atletas" action="Explorar conteúdos →" /><div className="video-grid">{videos.slice(0, 4).map(video => <VideoCard key={video[0]} video={video} go={go} />)}</div></section><section className="trust wrap"><div><span className="eyebrow blue">PROFISSIONAIS VERIFICADOS</span><h2>Experiência real.<br />Resultados confiáveis.</h2><p>Cada especialista passa por uma análise rigorosa de formação e experiência antes de entrar na plataforma.</p><button className="green" onClick={() => go('profissionais')}>Conheça os especialistas <ArrowUpRight size={14} /></button></div><div className="expert-row"><Expert name="Dra. Lara Nunes" role="Especialista esportiva" image={img.coach} /><Expert name="Caio Mendes" role="Força e condicionamento" image={img.athlete} /><Expert name="Marina Lopes" role="Nutrição esportiva" image={img.coach} /></div></section></main>; }
function SectionTitle({ eyebrow, title, action }) { return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button>{action}</button></div>; }
function VideoCard({ video, go }) { return <article className="video-card" onClick={() => go('detalhe')}><div className="video-image"><img src={video[3]} alt="" /><button className="play"><CirclePlay size={19} /></button><b>{video[2]}</b></div><span className="video-meta">{video[1]} <Star size={11} fill="currentColor" /> 4,9</span><h3>{video[0]}</h3><small>Caio Mendes <ShieldCheck size={11} /></small></article>; }
function Expert({ name, role, image }) { return <div className="expert"><img src={image} alt={name} /><strong>{name} <ShieldCheck size={11} /></strong><small>{role}</small></div>; }
function Explore({ go }) { return <main className="wrap page"><span className="eyebrow">BIBLIOTECA WELLFLIX</span><h1>Conteúdo para a sua evolução</h1><div className="search-large"><Search size={16} /> treino de performance <span>128 resultados</span></div><div className="explore-layout"><aside className="filters"><strong>Filtros</strong><button>Limpar</button><h5>Categoria</h5>{['Todos', 'Musculação', 'Yoga', 'Basquete', 'Nutrição', 'Risco'].map(x => <label key={x}><input type="checkbox" defaultChecked /> {x}</label>)}<h5>Avaliação</h5>{['★★★★★ 4,5+', '★★★★☆ 4,0+', '★★★☆☆ 3,0+'].map(x => <label key={x}><input type="checkbox" defaultChecked /> {x}</label>)}</aside><div className="results"><div className="result-head"><span>128 vídeos encontrados</span><button className="dark-button">Mais relevantes <ChevronDown size={13} /></button></div><div className="video-grid">{videos.map(v => <VideoCard key={v[0]} video={v} go={go} />)}</div></div></div></main>; }
function Plans({ go }) { return <main className="wrap page plans"><span className="eyebrow">ESCOLHA SUA EVOLUÇÃO</span><h1>Um plano para cada objetivo</h1><p>Conteúdo certificado, novos vídeos toda semana e liberdade para mudar de plano quando quiser.</p><div className="billing"><button>Mensal</button><button>Anual · -20%</button></div><div className="plan-grid">{[['Básico', 'R$ 29 /mês'], ['Pro', 'R$ 59 /mês'], ['Premium', 'R$ 89 /mês']].map(([name, price], i) => <article className={i === 1 ? 'plan featured-plan' : 'plan'} key={name}>{i === 1 && <span className="recommended">MAIS ESCOLHIDO</span>}<h2>{name}</h2><small>{i === 0 ? 'Comece com o essencial' : i === 1 ? 'Para quem treina sério' : 'Performance sem limites'}</small><strong>{price}</strong>{['Todas as categorias', 'Vídeos em Full HD', 'Planos e favoritos', 'Acesso em dispositivos'].slice(0, i + 2).map(x => <span className="check" key={x}><Check size={13} /> {x}</span>)}<button className={i === 1 ? 'green' : 'dark-button'} onClick={() => go('cadastro')}>{i === 1 ? 'Assinar Pro' : 'Escolher plano'} <ArrowUpRight size={13} /></button></article>)}</div><div className="payment"><h3>▣<br />Pagamento seguro e flexível</h3><p>Cartão de crédito, Pix ou boleto. Cancele quando quiser.</p><span>VISA</span><span>mastercard</span><span>PIX</span><span>boleto</span></div></main>; }
function Detail({ go }) { return <main className="wrap page detail"><div className="detail-main"><div className="player"><img src={img.athlete} alt="Treino de pernas" /><div className="player-bar"><i /><span>04:32 / 28:10</span> ⛶</div></div><span className="video-meta">MUSCULAÇÃO · INTERMEDIÁRIO</span><h1>Força total: treino de pernas sem atalhos</h1><p>Uma sessão completa para construir força, estabilidade e potência. Aprenda técnica, progressão de carga e os ajustes que protegem sua execução.</p><div className="coach-line"><img src={img.coach} alt="Caio Mendes" /><div><strong>Caio Mendes</strong><small>Preparador físico · CREF verificado</small></div><button className="dark-button">Ver perfil</button></div><h2>Comentários 248</h2>{['Treino excelente. A explicação da amplitude no agachamento mudou minha execução.', 'Didática muito clara e progressão bem estruturada!'].map((x, i) => <div className="comment" key={x}><b>{i ? 'ML' : 'JP'}</b><span><strong>{i ? 'Mia Lima' : 'João Pedro'}</strong>{x}</span></div>)}</div><aside className="side-videos"><h2>Continue evoluindo</h2>{videos.slice(0, 3).map(v => <VideoCard key={v[0]} video={v} go={go} />)}</aside></main>; }
function Professional() { return <main className="wrap page professional"><div className="cover" /><div className="pro-intro"><img src={img.coach} alt="Caio Mendes" /><div><h1>Caio Mendes <ShieldCheck size={16} /></h1><span className="eyebrow">Preparador físico e condicionamento</span><p>Especialista em performance esportiva e treinamento de força, com 12 anos de experiência preparando atletas.</p></div><button className="green">Seguir profissional <ArrowUpRight size={13} /></button></div><div className="stat-row"><Metric value="18,4 mil" label="alunos" /><Metric value="4,9" label="avaliação média" /><Metric value="42" label="vídeos publicados" /></div><SectionTitle title="Vídeos publicados" action="Ver todos →" /><div className="video-grid">{videos.slice(0, 3).map(v => <VideoCard key={v[0]} video={v} go={() => {}} />)}</div></main>; }
function Metric({ value, label }) { return <div className="metric"><strong>{value}</strong><small>{label}</small></div>; }
function Trails({ go }) { return <main className="wrap page"><span className="eyebrow">SUA JORNADA CONTINUA</span><h1>Trilhas de Conteúdo</h1><p>Programas completos, organizados em partes e episódios sequenciais para você evoluir no seu ritmo.</p><div className="trail-list">{['Programa de Musculação 12 Semanas', 'Yoga para Iniciantes', 'Recuperação Pós-Lesão'].map((x, i) => <article className="trail" key={x}><div><span className="eyebrow">{i === 0 ? 'MUSCULAÇÃO' : i === 1 ? 'YOGA' : 'RECUPERAÇÃO'}</span><h2>{x}</h2><p>Uma progressão completa com aulas guiadas e objetivos claros.</p></div><button className="green" onClick={() => go('detalhe')}>Continuar episódio</button><div className="trail-images">{videos.slice(i, i + 4).map(v => <img key={v[0]} src={v[3]} alt="" />)}</div></article>)}</div></main>; }
function Signup() { return <main className="signup"><div className="signup-art" style={{ backgroundImage: `url(${img.athlete})` }}><button className="logo">◉ WellFlix</button><div><h1>Consistência ganha<br />quando direção e<br />movimento jogam juntos.</h1><span>Conteúdo certificado para resultados reais.</span></div></div><form className="signup-form"><div className="tabs"><button>Entrar</button><button className="selected">Criar conta</button></div><h2>Que bom ter você aqui</h2><p>Entre para continuar sua evolução.</p>{['Nome completo', 'E-mail', 'Senha'].map((x, i) => <label key={x}>{x}<input placeholder={i === 0 ? 'Seu nome' : i === 1 ? 'voce@email.com' : '••••••••'} /></label>)}<label className="creator-check"><input type="checkbox" /> Quero me cadastrar como profissional</label><button className="green">Cadastrar <ArrowUpRight size={13} /></button></form></main>; }
function Footer() { return <footer><strong>WellFlix</strong><span>Conteúdos · Profissionais · Planos · Suporte · Termos</span><small>© 2026 WellFlix</small></footer>; }
+createRoot(document.getElementById('root')).render(<App />);
